n1 = float(input('Digite um valor: '))
n2 = float(input('Digite outro valor: '))
soma = int(n1 + n2)
subtrai = int(n1 - n2)
multiplicacao = int(n1 * n2)
divisao = int(n1 / n2)

print(soma)
print(subtrai)
print(multiplicacao)
print(divisao)